#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master"] || [ "$branch" = "main" ]; then
  echo "You can not push to master/main directly"
  exit 1
fi