#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


branch="$(git rev-parse --abbrev-ref HEAD)"
PROTECTED_BRANCHES="^(master|main)"

if [[ "$branch" =~ $PROTECTED_BRANCHES ]]; then
  echo "You can not commit into master/main branch"
  exit 1
fi