#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if ([ "$branch" = "master"] || ["$branch" = "main" ]); then
  echo "You can not commit into master/main branch"
  exit 1
fi

npm run lint
npm run test
