name: Pull request to main branch

on:
  push:
    branches: 
      - develop/*

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Test Lint
        run: npm run lint

      - name: Test coverage
        run: npm run test

      - name: Build
        run: npm run build

      - name: Execute Build
        run: cd build && node index.js

      - name: Upload results
        run: npm run upload

  create-pr-against-master-job:
    needs: test-code
    runs-on: ubuntu-latest
    name: create PR
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - run: exit 0
      - name: Create PR
        uses: Naomi-QF/naomi-deployment@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: develop/*
          BASE_BRANCH: main