name: QA deployment

on:
  push:
    branches: 
      - develop/*

jobs:
  test-code:
    environment:
      name: QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build

      - name: deploy to netflify
        run: netlify deploy -p --auth $secrets.NETLIFYAUTHTOKEN --site $secrets.NETSITEID

      - name: Test Lint
        run: npm run lint

      - name: Test coverage
        run: npm run test

      # - name: Execute Build
      #   run: cd build && node index.js

      # - name: Upload results
      #   run: npm run upload
  # deploy-to-netlify:
  #   needs: test-code
  #   runs-on: ubuntu-latest
  #   name: deploy to netlify
  #   steps:

  # create-pr-against-master-job:
  #   needs: test-code
  #   runs-on: ubuntu-latest
  #   name: create PR
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: '0'
  #     - run: exit 0
  #     - name: Create PR
  #       uses: Naomi-QF/naomi-deployment@main
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         HEAD_BRANCH: develop/*
  #         BASE_BRANCH: main